export type SvgStore = {addBox: string
addPerson: string
apartment: string
arrow: string
arrow2: string
arrow3: string
atico: string
bank: string
bath: string
bed: string
bellOff: string
bellOn: string
blog: string
bold: string
calculator: string
calendar: string
calendarAdd: string
car: string
checklist: string
close: string
cloud: string
cloudDone: string
color: string
compass: string
conservation: string
contract: string
copy: string
cottage: string
deal: string
diversity: string
edit: string
elevator: string
email: string
energy: string
error: string
evening: string
eye: string
eyeClosed: string
filters: string
googleDrive: string
graphic: string
groups: string
handshake: string
help: string
home: string
homeAdd: string
instagram: string
key: string
link: string
loading: string
logo: string
lupa: string
map: string
menu: string
money: string
office: string
pareado: string
parking: string
person: string
phone: string
play: string
qr: string
qrAdd: string
rate: string
review: string
robot: string
search: string
sell: string
settings: string
size: string
stats: string
store: string
store2: string
swap: string
sync: string
tick: string
trash: string
trastero: string
tree: string
twitter: string
underline: string
warning: string
wc: string
whatsapp: string
youtube: string
zoomIn: string
zoomOut: string
}